services:
  tranet-db:
    image: postgres:14.3
    restart: always
    ports:
      - '${DB_PORT:-5433}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_DATABASE}
    container_name: tranet-container
    volumes:
      - ./postgres:/var/lib/postgresql/data
